version: "3.9"

services:
  web:
    build: .
    container_name: boxing-web
    command: gunicorn boxing.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,217.114.4.253,devarena.ru,www.devarena.ru
      - DJANGO_SETTINGS_MODULE=boxing.settings
      - DB_NAME=boxing_db
      - DB_USER=Skuba4
      - DB_PASSWORD=12brasok98kobry
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    container_name: boxing-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=boxing_db
      - POSTGRES_USER=Skuba4
      - POSTGRES_PASSWORD=12brasok98kobry

  nginx:
    image: nginx:latest
    container_name: boxing-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
